version: "3.7"

services:
  php:
    container_name: php
    build:
      context: docker/php
      target: development
    volumes:
      - ./:/app
      - php-fpm:/usr/local/sbin/
    networks:
      - backend

  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - php-fpm:/run/php/
    networks:
      - backend
    depends_on:
      - php

volumes:
  php-fpm:

networks:
  backend: